apiVersion: v1
kind: ConfigMap
metadata:
  name: node-config
data:
  install.sh: |
    #!/bin/bash

    apt-get update
    apt install resolvconf -y
    cp /home/nodeconfig/OMP_Root_CA.crt /usr/local/share/ca-certificates/OMP_Root_CA.crt
    update-ca-certificates
    cp /home/nodeconfig/etc-hosts /etc/hosts
    cp /home/nodeconfig/resolv.conf /etc/resolvconf/resolv.conf.d/head
    systemctl restart resolvconf
    update-ca-certificates
    systemctl restart docker
    docker login omhqproget.domain.ompartners.com:443 -u api -p vkr5wMxytTliH7zJIM4X
